# Generated by Django 5.2 on 2025-04-29 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=100)),
                ('usia', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='hewan_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('individu', 'Individu'), ('organisasi', 'Organisasi')], max_length=10)),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('no_telepon', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('nama_organisasi', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adopsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_akhir', models.DateField()),
                ('kontribusi_finansial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_pembayaran', models.CharField(choices=[('tertunda', 'Tertunda'), ('lunas', 'Lunas'), ('dibatalkan', 'Dibatalkan')], default='tertunda', max_length=10)),
                ('alasan_adopsi', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopsi.adopter')),
                ('hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopsi.hewan')),
            ],
        ),
    ]
