# Generated by Django 5.2 on 2025-04-28 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('nama', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('jadwal', models.DateTimeField()),
                ('kapasitas_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Atraksi',
            fields=[
                ('fasilitas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='atraksi', serialize=False, to='biru.fasilitas')),
                ('lokasi', models.CharField(max_length=100)),
            ],
        ),
    ]
