# Generated by Django 5.2 on 2025-04-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biru', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atraksi',
        ),
        migrations.DeleteModel(
            name='Fasilitas',
        ),
    ]
